"""empty message

Revision ID: 7f97ebcd170e
Revises: 
Create Date: 2025-08-09 17:16:31.779688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f97ebcd170e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanicilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_adi', sa.String(length=100), nullable=False),
    sa.Column('sifre_hash', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kullanici_adi')
    )
    op.create_table('harcamalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=100), nullable=False),
    sa.Column('miktar', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('tarih', sa.String(length=100), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('harcamalar')
    op.drop_table('kullanicilar')
    # ### end Alembic commands ###
